package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Banners generated by hbm2java
 */
@Entity
@Table(name = "banners")
public class Banners implements java.io.Serializable {

	private int bannersId;
	private String bannersTitle;
	private String bannersUrl;
	private String bannersImage;
	private String bannersGroup;
	private String bannersHtmlText;
	private Integer expiresImpressions;
	private Date expiresDate;
	private Date dateScheduled;
	private Date dateAdded;
	private Date dateStatusChange;
	private int status;

	public Banners() {
	}

	public Banners(int bannersId, String bannersTitle, String bannersUrl,
			String bannersImage, String bannersGroup, Date dateAdded, int status) {
		this.bannersId = bannersId;
		this.bannersTitle = bannersTitle;
		this.bannersUrl = bannersUrl;
		this.bannersImage = bannersImage;
		this.bannersGroup = bannersGroup;
		this.dateAdded = dateAdded;
		this.status = status;
	}

	public Banners(int bannersId, String bannersTitle, String bannersUrl,
			String bannersImage, String bannersGroup, String bannersHtmlText,
			Integer expiresImpressions, Date expiresDate, Date dateScheduled,
			Date dateAdded, Date dateStatusChange, int status) {
		this.bannersId = bannersId;
		this.bannersTitle = bannersTitle;
		this.bannersUrl = bannersUrl;
		this.bannersImage = bannersImage;
		this.bannersGroup = bannersGroup;
		this.bannersHtmlText = bannersHtmlText;
		this.expiresImpressions = expiresImpressions;
		this.expiresDate = expiresDate;
		this.dateScheduled = dateScheduled;
		this.dateAdded = dateAdded;
		this.dateStatusChange = dateStatusChange;
		this.status = status;
	}

	@Id
	@Column(name = "banners_id", unique = true, nullable = false)
	public int getBannersId() {
		return this.bannersId;
	}

	public void setBannersId(int bannersId) {
		this.bannersId = bannersId;
	}

	@Column(name = "banners_title", nullable = false, length = 64)
	public String getBannersTitle() {
		return this.bannersTitle;
	}

	public void setBannersTitle(String bannersTitle) {
		this.bannersTitle = bannersTitle;
	}

	@Column(name = "banners_url", nullable = false)
	public String getBannersUrl() {
		return this.bannersUrl;
	}

	public void setBannersUrl(String bannersUrl) {
		this.bannersUrl = bannersUrl;
	}

	@Column(name = "banners_image", nullable = false, length = 64)
	public String getBannersImage() {
		return this.bannersImage;
	}

	public void setBannersImage(String bannersImage) {
		this.bannersImage = bannersImage;
	}

	@Column(name = "banners_group", nullable = false, length = 10)
	public String getBannersGroup() {
		return this.bannersGroup;
	}

	public void setBannersGroup(String bannersGroup) {
		this.bannersGroup = bannersGroup;
	}

	@Column(name = "banners_html_text")
	public String getBannersHtmlText() {
		return this.bannersHtmlText;
	}

	public void setBannersHtmlText(String bannersHtmlText) {
		this.bannersHtmlText = bannersHtmlText;
	}

	@Column(name = "expires_impressions")
	public Integer getExpiresImpressions() {
		return this.expiresImpressions;
	}

	public void setExpiresImpressions(Integer expiresImpressions) {
		this.expiresImpressions = expiresImpressions;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expires_date", length = 29)
	public Date getExpiresDate() {
		return this.expiresDate;
	}

	public void setExpiresDate(Date expiresDate) {
		this.expiresDate = expiresDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_scheduled", length = 29)
	public Date getDateScheduled() {
		return this.dateScheduled;
	}

	public void setDateScheduled(Date dateScheduled) {
		this.dateScheduled = dateScheduled;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_status_change", length = 29)
	public Date getDateStatusChange() {
		return this.dateStatusChange;
	}

	public void setDateStatusChange(Date dateStatusChange) {
		this.dateStatusChange = dateStatusChange;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

}
