package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ConfigurationGroup generated by hbm2java
 */
@Entity
@Table(name = "configuration_group")
public class ConfigurationGroup implements java.io.Serializable {

	private int configurationGroupId;
	private String configurationGroupTitle;
	private String configurationGroupDesc;
	private Integer sortOrder;
	private Integer visible;

	public ConfigurationGroup() {
	}

	public ConfigurationGroup(int configurationGroupId,
			String configurationGroupTitle, String configurationGroupDesc) {
		this.configurationGroupId = configurationGroupId;
		this.configurationGroupTitle = configurationGroupTitle;
		this.configurationGroupDesc = configurationGroupDesc;
	}

	public ConfigurationGroup(int configurationGroupId,
			String configurationGroupTitle, String configurationGroupDesc,
			Integer sortOrder, Integer visible) {
		this.configurationGroupId = configurationGroupId;
		this.configurationGroupTitle = configurationGroupTitle;
		this.configurationGroupDesc = configurationGroupDesc;
		this.sortOrder = sortOrder;
		this.visible = visible;
	}

	@Id
	@Column(name = "configuration_group_id", unique = true, nullable = false)
	public int getConfigurationGroupId() {
		return this.configurationGroupId;
	}

	public void setConfigurationGroupId(int configurationGroupId) {
		this.configurationGroupId = configurationGroupId;
	}

	@Column(name = "configuration_group_title", nullable = false, length = 64)
	public String getConfigurationGroupTitle() {
		return this.configurationGroupTitle;
	}

	public void setConfigurationGroupTitle(String configurationGroupTitle) {
		this.configurationGroupTitle = configurationGroupTitle;
	}

	@Column(name = "configuration_group_desc", nullable = false)
	public String getConfigurationGroupDesc() {
		return this.configurationGroupDesc;
	}

	public void setConfigurationGroupDesc(String configurationGroupDesc) {
		this.configurationGroupDesc = configurationGroupDesc;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Column(name = "visible")
	public Integer getVisible() {
		return this.visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

}
