package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Configuration generated by hbm2java
 */
@Entity
@Table(name = "configuration")
public class Configuration implements java.io.Serializable {

	private int configurationId;
	private String configurationTitle;
	private String configurationKey;
	private String configurationValue;
	private String configurationDescription;
	private int configurationGroupId;
	private Integer sortOrder;
	private Date lastModified;
	private Date dateAdded;
	private String useFunction;
	private String setFunction;

	public Configuration() {
	}

	public Configuration(int configurationId, String configurationTitle,
			String configurationKey, String configurationValue,
			String configurationDescription, int configurationGroupId,
			Date dateAdded) {
		this.configurationId = configurationId;
		this.configurationTitle = configurationTitle;
		this.configurationKey = configurationKey;
		this.configurationValue = configurationValue;
		this.configurationDescription = configurationDescription;
		this.configurationGroupId = configurationGroupId;
		this.dateAdded = dateAdded;
	}

	public Configuration(int configurationId, String configurationTitle,
			String configurationKey, String configurationValue,
			String configurationDescription, int configurationGroupId,
			Integer sortOrder, Date lastModified, Date dateAdded,
			String useFunction, String setFunction) {
		this.configurationId = configurationId;
		this.configurationTitle = configurationTitle;
		this.configurationKey = configurationKey;
		this.configurationValue = configurationValue;
		this.configurationDescription = configurationDescription;
		this.configurationGroupId = configurationGroupId;
		this.sortOrder = sortOrder;
		this.lastModified = lastModified;
		this.dateAdded = dateAdded;
		this.useFunction = useFunction;
		this.setFunction = setFunction;
	}

	@Id
	@Column(name = "configuration_id", unique = true, nullable = false)
	public int getConfigurationId() {
		return this.configurationId;
	}

	public void setConfigurationId(int configurationId) {
		this.configurationId = configurationId;
	}

	@Column(name = "configuration_title", nullable = false, length = 64)
	public String getConfigurationTitle() {
		return this.configurationTitle;
	}

	public void setConfigurationTitle(String configurationTitle) {
		this.configurationTitle = configurationTitle;
	}

	@Column(name = "configuration_key", nullable = false, length = 64)
	public String getConfigurationKey() {
		return this.configurationKey;
	}

	public void setConfigurationKey(String configurationKey) {
		this.configurationKey = configurationKey;
	}

	@Column(name = "configuration_value", nullable = false)
	public String getConfigurationValue() {
		return this.configurationValue;
	}

	public void setConfigurationValue(String configurationValue) {
		this.configurationValue = configurationValue;
	}

	@Column(name = "configuration_description", nullable = false)
	public String getConfigurationDescription() {
		return this.configurationDescription;
	}

	public void setConfigurationDescription(String configurationDescription) {
		this.configurationDescription = configurationDescription;
	}

	@Column(name = "configuration_group_id", nullable = false)
	public int getConfigurationGroupId() {
		return this.configurationGroupId;
	}

	public void setConfigurationGroupId(int configurationGroupId) {
		this.configurationGroupId = configurationGroupId;
	}

	@Column(name = "sort_order")
	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 29)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Column(name = "use_function")
	public String getUseFunction() {
		return this.useFunction;
	}

	public void setUseFunction(String useFunction) {
		this.useFunction = useFunction;
	}

	@Column(name = "set_function")
	public String getSetFunction() {
		return this.setFunction;
	}

	public void setSetFunction(String setFunction) {
		this.setFunction = setFunction;
	}

}
