package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomersInfo generated by hbm2java
 */
@Entity
@Table(name = "customers_info")
public class CustomersInfo implements java.io.Serializable {

	private int customersInfoId;
	private Date customersInfoDateLastLogon;
	private Integer customersInfoNumberOfLogon;
	private Date customersInfoDateCreated;
	private Date customersInfoDateModified;
	private Integer globalProductNotifications;

	public CustomersInfo() {
	}

	public CustomersInfo(int customersInfoId) {
		this.customersInfoId = customersInfoId;
	}

	public CustomersInfo(int customersInfoId, Date customersInfoDateLastLogon,
			Integer customersInfoNumberOfLogon, Date customersInfoDateCreated,
			Date customersInfoDateModified, Integer globalProductNotifications) {
		this.customersInfoId = customersInfoId;
		this.customersInfoDateLastLogon = customersInfoDateLastLogon;
		this.customersInfoNumberOfLogon = customersInfoNumberOfLogon;
		this.customersInfoDateCreated = customersInfoDateCreated;
		this.customersInfoDateModified = customersInfoDateModified;
		this.globalProductNotifications = globalProductNotifications;
	}

	@Id
	@Column(name = "customers_info_id", unique = true, nullable = false)
	public int getCustomersInfoId() {
		return this.customersInfoId;
	}

	public void setCustomersInfoId(int customersInfoId) {
		this.customersInfoId = customersInfoId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customers_info_date_last_logon", length = 29)
	public Date getCustomersInfoDateLastLogon() {
		return this.customersInfoDateLastLogon;
	}

	public void setCustomersInfoDateLastLogon(Date customersInfoDateLastLogon) {
		this.customersInfoDateLastLogon = customersInfoDateLastLogon;
	}

	@Column(name = "customers_info_number_of_logon")
	public Integer getCustomersInfoNumberOfLogon() {
		return this.customersInfoNumberOfLogon;
	}

	public void setCustomersInfoNumberOfLogon(Integer customersInfoNumberOfLogon) {
		this.customersInfoNumberOfLogon = customersInfoNumberOfLogon;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customers_info_date_created", length = 29)
	public Date getCustomersInfoDateCreated() {
		return this.customersInfoDateCreated;
	}

	public void setCustomersInfoDateCreated(Date customersInfoDateCreated) {
		this.customersInfoDateCreated = customersInfoDateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customers_info_date_modified", length = 29)
	public Date getCustomersInfoDateModified() {
		return this.customersInfoDateModified;
	}

	public void setCustomersInfoDateModified(Date customersInfoDateModified) {
		this.customersInfoDateModified = customersInfoDateModified;
	}

	@Column(name = "global_product_notifications")
	public Integer getGlobalProductNotifications() {
		return this.globalProductNotifications;
	}

	public void setGlobalProductNotifications(Integer globalProductNotifications) {
		this.globalProductNotifications = globalProductNotifications;
	}

}
