package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CustomersBasket generated by hbm2java
 */
@Entity
@Table(name = "customers_basket")
public class CustomersBasket implements java.io.Serializable {

	private int customersBasketId;
	private int customersId;
	private String productsId;
	private int customersBasketQuantity;
	private BigDecimal finalPrice;
	private String customersBasketDateAdded;

	public CustomersBasket() {
	}

	public CustomersBasket(int customersBasketId, int customersId,
			String productsId, int customersBasketQuantity,
			BigDecimal finalPrice) {
		this.customersBasketId = customersBasketId;
		this.customersId = customersId;
		this.productsId = productsId;
		this.customersBasketQuantity = customersBasketQuantity;
		this.finalPrice = finalPrice;
	}

	public CustomersBasket(int customersBasketId, int customersId,
			String productsId, int customersBasketQuantity,
			BigDecimal finalPrice, String customersBasketDateAdded) {
		this.customersBasketId = customersBasketId;
		this.customersId = customersId;
		this.productsId = productsId;
		this.customersBasketQuantity = customersBasketQuantity;
		this.finalPrice = finalPrice;
		this.customersBasketDateAdded = customersBasketDateAdded;
	}

	@Id
	@Column(name = "customers_basket_id", unique = true, nullable = false)
	public int getCustomersBasketId() {
		return this.customersBasketId;
	}

	public void setCustomersBasketId(int customersBasketId) {
		this.customersBasketId = customersBasketId;
	}

	@Column(name = "customers_id", nullable = false)
	public int getCustomersId() {
		return this.customersId;
	}

	public void setCustomersId(int customersId) {
		this.customersId = customersId;
	}

	@Column(name = "products_id", nullable = false)
	public String getProductsId() {
		return this.productsId;
	}

	public void setProductsId(String productsId) {
		this.productsId = productsId;
	}

	@Column(name = "customers_basket_quantity", nullable = false)
	public int getCustomersBasketQuantity() {
		return this.customersBasketQuantity;
	}

	public void setCustomersBasketQuantity(int customersBasketQuantity) {
		this.customersBasketQuantity = customersBasketQuantity;
	}

	@Column(name = "final_price", nullable = false, precision = 15, scale = 4)
	public BigDecimal getFinalPrice() {
		return this.finalPrice;
	}

	public void setFinalPrice(BigDecimal finalPrice) {
		this.finalPrice = finalPrice;
	}

	@Column(name = "customers_basket_date_added", length = 8)
	public String getCustomersBasketDateAdded() {
		return this.customersBasketDateAdded;
	}

	public void setCustomersBasketDateAdded(String customersBasketDateAdded) {
		this.customersBasketDateAdded = customersBasketDateAdded;
	}

}
