package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * KkCookieId generated by hbm2java
 */
@Embeddable
public class ExCookieId implements java.io.Serializable {

	private String customerUuid;
	private String attributeId;

	public ExCookieId() {
	}

	public ExCookieId(String customerUuid, String attributeId) {
		this.customerUuid = customerUuid;
		this.attributeId = attributeId;
	}

	@Column(name = "customer_uuid", nullable = false, length = 128)
	public String getCustomerUuid() {
		return this.customerUuid;
	}

	public void setCustomerUuid(String customerUuid) {
		this.customerUuid = customerUuid;
	}

	@Column(name = "attribute_id", nullable = false, length = 64)
	public String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(String attributeId) {
		this.attributeId = attributeId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ExCookieId))
			return false;
		ExCookieId castOther = (ExCookieId) other;

		return ((this.getCustomerUuid() == castOther.getCustomerUuid()) || (this
				.getCustomerUuid() != null
				&& castOther.getCustomerUuid() != null && this
				.getCustomerUuid().equals(castOther.getCustomerUuid())))
				&& ((this.getAttributeId() == castOther.getAttributeId()) || (this
						.getAttributeId() != null
						&& castOther.getAttributeId() != null && this
						.getAttributeId().equals(castOther.getAttributeId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCustomerUuid() == null ? 0 : this.getCustomerUuid()
						.hashCode());
		result = 37
				* result
				+ (getAttributeId() == null ? 0 : this.getAttributeId()
						.hashCode());
		return result;
	}

}
