package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KkCookie generated by hbm2java
 */
@Entity
@Table(name = "Ex_cookie")
public class ExCookie implements java.io.Serializable {

	private ExCookieId id;
	private String attributeValue;
	private Date dateAdded;
	private Date lastRead;
	private Date lastModified;

	public ExCookie() {
	}

	public ExCookie(ExCookieId id, Date dateAdded) {
		this.id = id;
		this.dateAdded = dateAdded;
	}

	public ExCookie(ExCookieId id, String attributeValue, Date dateAdded,
			Date lastRead, Date lastModified) {
		this.id = id;
		this.attributeValue = attributeValue;
		this.dateAdded = dateAdded;
		this.lastRead = lastRead;
		this.lastModified = lastModified;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerUuid", column = @Column(name = "customer_uuid", nullable = false, length = 128)),
			@AttributeOverride(name = "attributeId", column = @Column(name = "attribute_id", nullable = false, length = 64)) })
	public ExCookieId getId() {
		return this.id;
	}

	public void setId(ExCookieId id) {
		this.id = id;
	}

	@Column(name = "attribute_value", length = 256)
	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", nullable = false, length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_read", length = 29)
	public Date getLastRead() {
		return this.lastRead;
	}

	public void setLastRead(Date lastRead) {
		this.lastRead = lastRead;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 29)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
