package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ManufacturersInfo generated by hbm2java
 */
@Entity
@Table(name = "manufacturers_info")
public class ManufacturersInfo implements java.io.Serializable {

	private ManufacturersInfoId id;
	private String manufacturersUrl;
	private int urlClicked;
	private Date dateLastClick;

	public ManufacturersInfo() {
	}

	public ManufacturersInfo(ManufacturersInfoId id, String manufacturersUrl,
			int urlClicked) {
		this.id = id;
		this.manufacturersUrl = manufacturersUrl;
		this.urlClicked = urlClicked;
	}

	public ManufacturersInfo(ManufacturersInfoId id, String manufacturersUrl,
			int urlClicked, Date dateLastClick) {
		this.id = id;
		this.manufacturersUrl = manufacturersUrl;
		this.urlClicked = urlClicked;
		this.dateLastClick = dateLastClick;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "manufacturersId", column = @Column(name = "manufacturers_id", nullable = false)),
			@AttributeOverride(name = "languagesId", column = @Column(name = "languages_id", nullable = false)) })
	public ManufacturersInfoId getId() {
		return this.id;
	}

	public void setId(ManufacturersInfoId id) {
		this.id = id;
	}

	@Column(name = "manufacturers_url", nullable = false)
	public String getManufacturersUrl() {
		return this.manufacturersUrl;
	}

	public void setManufacturersUrl(String manufacturersUrl) {
		this.manufacturersUrl = manufacturersUrl;
	}

	@Column(name = "url_clicked", nullable = false)
	public int getUrlClicked() {
		return this.urlClicked;
	}

	public void setUrlClicked(int urlClicked) {
		this.urlClicked = urlClicked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_last_click", length = 29)
	public Date getDateLastClick() {
		return this.dateLastClick;
	}

	public void setDateLastClick(Date dateLastClick) {
		this.dateLastClick = dateLastClick;
	}

}
