package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Manufacturers generated by hbm2java
 */
@Entity
@Table(name = "manufacturers")
public class Manufacturers implements java.io.Serializable {

	private int manufacturersId;
	private String manufacturersName;
	private String manufacturersImage;
	private Date dateAdded;
	private Date lastModified;

	public Manufacturers() {
	}

	public Manufacturers(int manufacturersId, String manufacturersName) {
		this.manufacturersId = manufacturersId;
		this.manufacturersName = manufacturersName;
	}

	public Manufacturers(int manufacturersId, String manufacturersName,
			String manufacturersImage, Date dateAdded, Date lastModified) {
		this.manufacturersId = manufacturersId;
		this.manufacturersName = manufacturersName;
		this.manufacturersImage = manufacturersImage;
		this.dateAdded = dateAdded;
		this.lastModified = lastModified;
	}

	@Id
	@Column(name = "manufacturers_id", unique = true, nullable = false)
	public int getManufacturersId() {
		return this.manufacturersId;
	}

	public void setManufacturersId(int manufacturersId) {
		this.manufacturersId = manufacturersId;
	}

	@Column(name = "manufacturers_name", nullable = false, length = 32)
	public String getManufacturersName() {
		return this.manufacturersName;
	}

	public void setManufacturersName(String manufacturersName) {
		this.manufacturersName = manufacturersName;
	}

	@Column(name = "manufacturers_image", length = 64)
	public String getManufacturersImage() {
		return this.manufacturersImage;
	}

	public void setManufacturersImage(String manufacturersImage) {
		this.manufacturersImage = manufacturersImage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 29)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
