package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrdersProducts generated by hbm2java
 */
@Entity
@Table(name = "orders_products")
public class OrdersProducts implements java.io.Serializable {

	private int ordersProductsId;
	private Orders orders;
	private int productsId;

	public OrdersProducts() {
	}

	public OrdersProducts(int ordersProductsId, Orders orders, int productsId) {
		this.ordersProductsId = ordersProductsId;
		this.orders = orders;
		this.productsId = productsId;
	}

	@Id
	@Column(name = "orders_products_id", unique = true, nullable = false)
	public int getOrdersProductsId() {
		return this.ordersProductsId;
	}

	public void setOrdersProductsId(int ordersProductsId) {
		this.ordersProductsId = ordersProductsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orders_id", nullable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "products_id", nullable = false)
	public int getProductsId() {
		return this.productsId;
	}

	public void setProductsId(int productsId) {
		this.productsId = productsId;
	}

}
