package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OrdersStatus generated by hbm2java
 */
@Entity
@Table(name = "orders_status")
public class OrdersStatus implements java.io.Serializable {

	private OrdersStatusId id;
	private String ordersStatusName;

	public OrdersStatus() {
	}

	public OrdersStatus(OrdersStatusId id, String ordersStatusName) {
		this.id = id;
		this.ordersStatusName = ordersStatusName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordersStatusId", column = @Column(name = "orders_status_id", nullable = false)),
			@AttributeOverride(name = "languageId", column = @Column(name = "language_id", nullable = false)) })
	public OrdersStatusId getId() {
		return this.id;
	}

	public void setId(OrdersStatusId id) {
		this.id = id;
	}

	@Column(name = "orders_status_name", nullable = false, length = 32)
	public String getOrdersStatusName() {
		return this.ordersStatusName;
	}

	public void setOrdersStatusName(String ordersStatusName) {
		this.ordersStatusName = ordersStatusName;
	}

}
