package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersStatusId generated by hbm2java
 */
@Embeddable
public class OrdersStatusId implements java.io.Serializable {

	private int ordersStatusId;
	private int languageId;

	public OrdersStatusId() {
	}

	public OrdersStatusId(int ordersStatusId, int languageId) {
		this.ordersStatusId = ordersStatusId;
		this.languageId = languageId;
	}

	@Column(name = "orders_status_id", nullable = false)
	public int getOrdersStatusId() {
		return this.ordersStatusId;
	}

	public void setOrdersStatusId(int ordersStatusId) {
		this.ordersStatusId = ordersStatusId;
	}

	@Column(name = "language_id", nullable = false)
	public int getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(int languageId) {
		this.languageId = languageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersStatusId))
			return false;
		OrdersStatusId castOther = (OrdersStatusId) other;

		return (this.getOrdersStatusId() == castOther.getOrdersStatusId())
				&& (this.getLanguageId() == castOther.getLanguageId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrdersStatusId();
		result = 37 * result + this.getLanguageId();
		return result;
	}

}
