package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProductsVendors generated by hbm2java
 */
@Entity
@Table(name = "products_vendors")
public class ProductsVendors implements java.io.Serializable {

	private int productsVendorsId;
	private Vendors vendors;
	private int productsId;

	public ProductsVendors() {
	}

	public ProductsVendors(int productsVendorsId, Vendors vendors,
			int productsId) {
		this.productsVendorsId = productsVendorsId;
		this.vendors = vendors;
		this.productsId = productsId;
	}

	@Id
	@Column(name = "products_vendors_id", unique = true, nullable = false)
	public int getProductsVendorsId() {
		return this.productsVendorsId;
	}

	public void setProductsVendorsId(int productsVendorsId) {
		this.productsVendorsId = productsVendorsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "vendors_id", nullable = false)
	public Vendors getVendors() {
		return this.vendors;
	}

	public void setVendors(Vendors vendors) {
		this.vendors = vendors;
	}

	@Column(name = "products_id", nullable = false)
	public int getProductsId() {
		return this.productsId;
	}

	public void setProductsId(int productsId) {
		this.productsId = productsId;
	}

}
