package com.app.pojo;

// Generated 3 May, 2015 12:36:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name = "products", schema = "public")
public class Products implements java.io.Serializable {

	private int productsId;
	private Integer categoriesId;
	private Integer productsQuantity;
	private String productsModel;
	private String productsImage;
	private BigDecimal productsPrice;
	private Date productsDateAdded;
	private Date productsLastModified;
	private Date productsDateAvailable;
	private BigDecimal productsWeight;
	private Integer productsStatus;
	private String productsUrl;
	private Integer productsViewed;
	private Integer manufacturersId;
	private Integer productsOrdered;

	private Categories categories;
	
	
	//bi-directional many-to-one association to Categories
    @ManyToOne(cascade={CascadeType.ALL})
	@JoinColumn(name="categoriesId")
	public Categories getCategories() {
		return this.categories;
	}

	public void setAlbum(Categories categories) {
		
		this.categories = categories;
	}
	
	
	public Products() {
	}

	public Products(int productsId) {
		this.productsId = productsId;
	}

	public Products(int productsId, Integer categoriesId,
			Integer productsQuantity, String productsModel,
			String productsImage, BigDecimal productsPrice,
			Date productsDateAdded, Date productsLastModified,
			Date productsDateAvailable, BigDecimal productsWeight,
			Integer productsStatus, String productsUrl, Integer productsViewed,
			Integer manufacturersId, Integer productsOrdered) {
		this.productsId = productsId;
		this.categoriesId = categoriesId;
		this.productsQuantity = productsQuantity;
		this.productsModel = productsModel;
		this.productsImage = productsImage;
		this.productsPrice = productsPrice;
		this.productsDateAdded = productsDateAdded;
		this.productsLastModified = productsLastModified;
		this.productsDateAvailable = productsDateAvailable;
		this.productsWeight = productsWeight;
		this.productsStatus = productsStatus;
		this.productsUrl = productsUrl;
		this.productsViewed = productsViewed;
		this.manufacturersId = manufacturersId;
		this.productsOrdered = productsOrdered;
	}

	@Id
	@Column(name = "products_id", unique = true, nullable = false)
	public int getProductsId() {
		return this.productsId;
	}

	public void setProductsId(int productsId) {
		this.productsId = productsId;
	}

	@Column(name = "categories_id")
	public Integer getCategoriesId() {
		return this.categoriesId;
	}

	public void setCategoriesId(Integer categoriesId) {
		this.categoriesId = categoriesId;
	}

	@Column(name = "products_quantity")
	public Integer getProductsQuantity() {
		return this.productsQuantity;
	}

	public void setProductsQuantity(Integer productsQuantity) {
		this.productsQuantity = productsQuantity;
	}

	@Column(name = "products_model", length = 12)
	public String getProductsModel() {
		return this.productsModel;
	}

	public void setProductsModel(String productsModel) {
		this.productsModel = productsModel;
	}

	@Column(name = "products_image", length = 64)
	public String getProductsImage() {
		return this.productsImage;
	}

	public void setProductsImage(String productsImage) {
		this.productsImage = productsImage;
	}

	@Column(name = "products_price", precision = 15, scale = 4)
	public BigDecimal getProductsPrice() {
		return this.productsPrice;
	}

	public void setProductsPrice(BigDecimal productsPrice) {
		this.productsPrice = productsPrice;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "products_date_added", length = 29)
	public Date getProductsDateAdded() {
		return this.productsDateAdded;
	}

	public void setProductsDateAdded(Date productsDateAdded) {
		this.productsDateAdded = productsDateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "products_last_modified", length = 29)
	public Date getProductsLastModified() {
		return this.productsLastModified;
	}

	public void setProductsLastModified(Date productsLastModified) {
		this.productsLastModified = productsLastModified;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "products_date_available", length = 29)
	public Date getProductsDateAvailable() {
		return this.productsDateAvailable;
	}

	public void setProductsDateAvailable(Date productsDateAvailable) {
		this.productsDateAvailable = productsDateAvailable;
	}

	@Column(name = "products_weight", precision = 5)
	public BigDecimal getProductsWeight() {
		return this.productsWeight;
	}

	public void setProductsWeight(BigDecimal productsWeight) {
		this.productsWeight = productsWeight;
	}

	@Column(name = "products_status")
	public Integer getProductsStatus() {
		return this.productsStatus;
	}

	public void setProductsStatus(Integer productsStatus) {
		this.productsStatus = productsStatus;
	}

	@Column(name = "products_url")
	public String getProductsUrl() {
		return this.productsUrl;
	}

	public void setProductsUrl(String productsUrl) {
		this.productsUrl = productsUrl;
	}

	@Column(name = "products_viewed")
	public Integer getProductsViewed() {
		return this.productsViewed;
	}

	public void setProductsViewed(Integer productsViewed) {
		this.productsViewed = productsViewed;
	}

	@Column(name = "manufacturers_id")
	public Integer getManufacturersId() {
		return this.manufacturersId;
	}

	public void setManufacturersId(Integer manufacturersId) {
		this.manufacturersId = manufacturersId;
	}

	@Column(name = "products_ordered")
	public Integer getProductsOrdered() {
		return this.productsOrdered;
	}

	public void setProductsOrdered(Integer productsOrdered) {
		this.productsOrdered = productsOrdered;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((categoriesId == null) ? 0 : categoriesId.hashCode());
		result = prime * result
				+ ((manufacturersId == null) ? 0 : manufacturersId.hashCode());
		result = prime
				* result
				+ ((productsDateAdded == null) ? 0 : productsDateAdded
						.hashCode());
		result = prime
				* result
				+ ((productsDateAvailable == null) ? 0 : productsDateAvailable
						.hashCode());
		result = prime * result + productsId;
		result = prime * result
				+ ((productsImage == null) ? 0 : productsImage.hashCode());
		result = prime
				* result
				+ ((productsLastModified == null) ? 0 : productsLastModified
						.hashCode());
		result = prime * result
				+ ((productsModel == null) ? 0 : productsModel.hashCode());
		result = prime * result
				+ ((productsOrdered == null) ? 0 : productsOrdered.hashCode());
		result = prime * result
				+ ((productsPrice == null) ? 0 : productsPrice.hashCode());
		result = prime
				* result
				+ ((productsQuantity == null) ? 0 : productsQuantity.hashCode());
		result = prime * result
				+ ((productsStatus == null) ? 0 : productsStatus.hashCode());
		result = prime * result
				+ ((productsUrl == null) ? 0 : productsUrl.hashCode());
		result = prime * result
				+ ((productsViewed == null) ? 0 : productsViewed.hashCode());
		result = prime * result
				+ ((productsWeight == null) ? 0 : productsWeight.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Products other = (Products) obj;
		if (categoriesId == null) {
			if (other.categoriesId != null)
				return false;
		} else if (!categoriesId.equals(other.categoriesId))
			return false;
		if (manufacturersId == null) {
			if (other.manufacturersId != null)
				return false;
		} else if (!manufacturersId.equals(other.manufacturersId))
			return false;
		if (productsDateAdded == null) {
			if (other.productsDateAdded != null)
				return false;
		} else if (!productsDateAdded.equals(other.productsDateAdded))
			return false;
		if (productsDateAvailable == null) {
			if (other.productsDateAvailable != null)
				return false;
		} else if (!productsDateAvailable.equals(other.productsDateAvailable))
			return false;
		if (productsId != other.productsId)
			return false;
		if (productsImage == null) {
			if (other.productsImage != null)
				return false;
		} else if (!productsImage.equals(other.productsImage))
			return false;
		if (productsLastModified == null) {
			if (other.productsLastModified != null)
				return false;
		} else if (!productsLastModified.equals(other.productsLastModified))
			return false;
		if (productsModel == null) {
			if (other.productsModel != null)
				return false;
		} else if (!productsModel.equals(other.productsModel))
			return false;
		if (productsOrdered == null) {
			if (other.productsOrdered != null)
				return false;
		} else if (!productsOrdered.equals(other.productsOrdered))
			return false;
		if (productsPrice == null) {
			if (other.productsPrice != null)
				return false;
		} else if (!productsPrice.equals(other.productsPrice))
			return false;
		if (productsQuantity == null) {
			if (other.productsQuantity != null)
				return false;
		} else if (!productsQuantity.equals(other.productsQuantity))
			return false;
		if (productsStatus == null) {
			if (other.productsStatus != null)
				return false;
		} else if (!productsStatus.equals(other.productsStatus))
			return false;
		if (productsUrl == null) {
			if (other.productsUrl != null)
				return false;
		} else if (!productsUrl.equals(other.productsUrl))
			return false;
		if (productsViewed == null) {
			if (other.productsViewed != null)
				return false;
		} else if (!productsViewed.equals(other.productsViewed))
			return false;
		if (productsWeight == null) {
			if (other.productsWeight != null)
				return false;
		} else if (!productsWeight.equals(other.productsWeight))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Products [productsId=" + productsId + ", categoriesId="
				+ categoriesId + ", productsQuantity=" + productsQuantity
				+ ", productsModel=" + productsModel + ", productsImage="
				+ productsImage + ", productsPrice=" + productsPrice
				+ ", productsDateAdded=" + productsDateAdded
				+ ", productsLastModified=" + productsLastModified
				+ ", productsDateAvailable=" + productsDateAvailable
				+ ", productsWeight=" + productsWeight + ", productsStatus="
				+ productsStatus + ", productsUrl=" + productsUrl
				+ ", productsViewed=" + productsViewed + ", manufacturersId="
				+ manufacturersId + ", productsOrdered=" + productsOrdered
				+ "]";
	}

	
	
}
