package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reviews generated by hbm2java
 */
@Entity
@Table(name = "reviews")
public class Reviews implements java.io.Serializable {

	private int reviewsId;
	private Products products;
	private Customers customers;
	private Integer reviewsRating;
	private String reviewText;
	private Date dateAdded;
	private Date lastModified;
	private int reviewsRead;

	public Reviews() {
	}

	public Reviews(int reviewsId, Products products, Customers customers,
			int reviewsRead) {
		this.reviewsId = reviewsId;
		this.products = products;
		this.customers = customers;
		this.reviewsRead = reviewsRead;
	}

	public Reviews(int reviewsId, Products products, Customers customers,
			Integer reviewsRating, String reviewText, Date dateAdded,
			Date lastModified, int reviewsRead) {
		this.reviewsId = reviewsId;
		this.products = products;
		this.customers = customers;
		this.reviewsRating = reviewsRating;
		this.reviewText = reviewText;
		this.dateAdded = dateAdded;
		this.lastModified = lastModified;
		this.reviewsRead = reviewsRead;
	}

	@Id
	@Column(name = "reviews_id", unique = true, nullable = false)
	public int getReviewsId() {
		return this.reviewsId;
	}

	public void setReviewsId(int reviewsId) {
		this.reviewsId = reviewsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "products_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customers_id", nullable = false)
	public Customers getCustomers() {
		return this.customers;
	}

	public void setCustomers(Customers customers) {
		this.customers = customers;
	}

	@Column(name = "reviews_rating")
	public Integer getReviewsRating() {
		return this.reviewsRating;
	}

	public void setReviewsRating(Integer reviewsRating) {
		this.reviewsRating = reviewsRating;
	}

	@Column(name = "review_text",length = 1000)
	public String getReviewText() {
		return this.reviewText;
	}

	public void setReviewText(String reviewText) {
		this.reviewText = reviewText;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 29)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@Column(name = "reviews_read", nullable = false)
	public int getReviewsRead() {
		return this.reviewsRead;
	}

	public void setReviewsRead(int reviewsRead) {
		this.reviewsRead = reviewsRead;
	}

}
