package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sessions generated by hbm2java
 */
@Entity
@Table(name = "sessions")
public class Sessions implements java.io.Serializable {

	private String sesskey;
	private int expiry;
	private Integer customerId;
	private String value;
	private String storeId;
	private String custom1;
	private String custom2;
	private String custom3;
	private String custom4;
	private String custom5;

	public Sessions() {
	}

	public Sessions(String sesskey, int expiry) {
		this.sesskey = sesskey;
		this.expiry = expiry;
	}

	public Sessions(String sesskey, int expiry, Integer customerId,
			String value, String storeId, String custom1, String custom2,
			String custom3, String custom4, String custom5) {
		this.sesskey = sesskey;
		this.expiry = expiry;
		this.customerId = customerId;
		this.value = value;
		this.storeId = storeId;
		this.custom1 = custom1;
		this.custom2 = custom2;
		this.custom3 = custom3;
		this.custom4 = custom4;
		this.custom5 = custom5;
	}

	@Id
	@Column(name = "sesskey", unique = true, nullable = false, length = 32)
	public String getSesskey() {
		return this.sesskey;
	}

	public void setSesskey(String sesskey) {
		this.sesskey = sesskey;
	}

	@Column(name = "expiry", nullable = false)
	public int getExpiry() {
		return this.expiry;
	}

	public void setExpiry(int expiry) {
		this.expiry = expiry;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "value", length = 256)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "store_id", length = 64)
	public String getStoreId() {
		return this.storeId;
	}

	public void setStoreId(String storeId) {
		this.storeId = storeId;
	}

	@Column(name = "custom1", length = 128)
	public String getCustom1() {
		return this.custom1;
	}

	public void setCustom1(String custom1) {
		this.custom1 = custom1;
	}

	@Column(name = "custom2", length = 128)
	public String getCustom2() {
		return this.custom2;
	}

	public void setCustom2(String custom2) {
		this.custom2 = custom2;
	}

	@Column(name = "custom3", length = 128)
	public String getCustom3() {
		return this.custom3;
	}

	public void setCustom3(String custom3) {
		this.custom3 = custom3;
	}

	@Column(name = "custom4", length = 128)
	public String getCustom4() {
		return this.custom4;
	}

	public void setCustom4(String custom4) {
		this.custom4 = custom4;
	}

	@Column(name = "custom5", length = 128)
	public String getCustom5() {
		return this.custom5;
	}

	public void setCustom5(String custom5) {
		this.custom5 = custom5;
	}

}
