package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vendors generated by hbm2java
 */
@Entity
@Table(name = "vendors")
public class Vendors implements java.io.Serializable {

	private int vendorsId;
	private AddressBook addressBook;
	private String vendorsName;
	private String vendorsImage;
	private Date dateAdded;
	private Date lastModified;
	private Set<ProductsVendors> productsVendorses = new HashSet<ProductsVendors>(
			0);
	private Set<AddressBook> addressBooks = new HashSet<AddressBook>(0);

	public Vendors() {
	}

	public Vendors(int vendorsId, AddressBook addressBook, String vendorsName) {
		this.vendorsId = vendorsId;
		this.addressBook = addressBook;
		this.vendorsName = vendorsName;
	}

	public Vendors(int vendorsId, AddressBook addressBook, String vendorsName,
			String vendorsImage, Date dateAdded, Date lastModified,
			Set<ProductsVendors> productsVendorses,
			Set<AddressBook> addressBooks) {
		this.vendorsId = vendorsId;
		this.addressBook = addressBook;
		this.vendorsName = vendorsName;
		this.vendorsImage = vendorsImage;
		this.dateAdded = dateAdded;
		this.lastModified = lastModified;
		this.productsVendorses = productsVendorses;
		this.addressBooks = addressBooks;
	}

	@Id
	@Column(name = "vendors_id", unique = true, nullable = false)
	public int getVendorsId() {
		return this.vendorsId;
	}

	public void setVendorsId(int vendorsId) {
		this.vendorsId = vendorsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "address_book_id", nullable = false)
	public AddressBook getAddressBook() {
		return this.addressBook;
	}

	public void setAddressBook(AddressBook addressBook) {
		this.addressBook = addressBook;
	}

	@Column(name = "vendors_name", nullable = false, length = 32)
	public String getVendorsName() {
		return this.vendorsName;
	}

	public void setVendorsName(String vendorsName) {
		this.vendorsName = vendorsName;
	}

	@Column(name = "vendors_image", length = 64)
	public String getVendorsImage() {
		return this.vendorsImage;
	}

	public void setVendorsImage(String vendorsImage) {
		this.vendorsImage = vendorsImage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_added", length = 29)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 29)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<ProductsVendors> getProductsVendorses() {
		return this.productsVendorses;
	}

	public void setProductsVendorses(Set<ProductsVendors> productsVendorses) {
		this.productsVendorses = productsVendorses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendors")
	public Set<AddressBook> getAddressBooks() {
		return this.addressBooks;
	}

	public void setAddressBooks(Set<AddressBook> addressBooks) {
		this.addressBooks = addressBooks;
	}

}
