package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendorsInfo generated by hbm2java
 */
@Entity
@Table(name = "vendors_info")
public class VendorsInfo implements java.io.Serializable {

	private int vendorsId;
	private String vendorsUrl;
	private int urlClicked;
	private Date dateLastClick;

	public VendorsInfo() {
	}

	public VendorsInfo(int vendorsId, String vendorsUrl, int urlClicked) {
		this.vendorsId = vendorsId;
		this.vendorsUrl = vendorsUrl;
		this.urlClicked = urlClicked;
	}

	public VendorsInfo(int vendorsId, String vendorsUrl, int urlClicked,
			Date dateLastClick) {
		this.vendorsId = vendorsId;
		this.vendorsUrl = vendorsUrl;
		this.urlClicked = urlClicked;
		this.dateLastClick = dateLastClick;
	}

	@Id
	@Column(name = "vendors_id", unique = true, nullable = false)
	public int getVendorsId() {
		return this.vendorsId;
	}

	public void setVendorsId(int vendorsId) {
		this.vendorsId = vendorsId;
	}

	@Column(name = "vendors_url", nullable = false)
	public String getVendorsUrl() {
		return this.vendorsUrl;
	}

	public void setVendorsUrl(String vendorsUrl) {
		this.vendorsUrl = vendorsUrl;
	}

	@Column(name = "url_clicked", nullable = false)
	public int getUrlClicked() {
		return this.urlClicked;
	}

	public void setUrlClicked(int urlClicked) {
		this.urlClicked = urlClicked;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_last_click", length = 29)
	public Date getDateLastClick() {
		return this.dateLastClick;
	}

	public void setDateLastClick(Date dateLastClick) {
		this.dateLastClick = dateLastClick;
	}

}
