package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WhosOnline generated by hbm2java
 */
@Entity
@Table(name = "whos_online")
public class WhosOnline implements java.io.Serializable {

	private WhosOnlineId id;

	public WhosOnline() {
	}

	public WhosOnline(WhosOnlineId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "customerId", column = @Column(name = "customer_id")),
			@AttributeOverride(name = "fullName", column = @Column(name = "full_name", nullable = false, length = 64)),
			@AttributeOverride(name = "sessionId", column = @Column(name = "session_id", nullable = false, length = 128)),
			@AttributeOverride(name = "ipAddress", column = @Column(name = "ip_address", nullable = false, length = 15)),
			@AttributeOverride(name = "timeEntry", column = @Column(name = "time_entry", nullable = false, length = 14)),
			@AttributeOverride(name = "timeLastClick", column = @Column(name = "time_last_click", nullable = false, length = 14)),
			@AttributeOverride(name = "lastPageUrl", column = @Column(name = "last_page_url", nullable = false, length = 64)) })
	public WhosOnlineId getId() {
		return this.id;
	}

	public void setId(WhosOnlineId id) {
		this.id = id;
	}

}
