package com.app.pojo;

// Generated 6 Jun, 2015 8:21:44 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WhosOnlineId generated by hbm2java
 */
@Embeddable
public class WhosOnlineId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer customerId;
	private String fullName;
	private String sessionId;
	private String ipAddress;
	private String timeEntry;
	private String timeLastClick;
	private String lastPageUrl;

	public WhosOnlineId() {
	}

	public WhosOnlineId(String fullName, String sessionId, String ipAddress,
			String timeEntry, String timeLastClick, String lastPageUrl) {
		this.fullName = fullName;
		this.sessionId = sessionId;
		this.ipAddress = ipAddress;
		this.timeEntry = timeEntry;
		this.timeLastClick = timeLastClick;
		this.lastPageUrl = lastPageUrl;
	}

	public WhosOnlineId(Integer customerId, String fullName, String sessionId,
			String ipAddress, String timeEntry, String timeLastClick,
			String lastPageUrl) {
		this.customerId = customerId;
		this.fullName = fullName;
		this.sessionId = sessionId;
		this.ipAddress = ipAddress;
		this.timeEntry = timeEntry;
		this.timeLastClick = timeLastClick;
		this.lastPageUrl = lastPageUrl;
	}

	@Column(name = "customer_id")
	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	@Column(name = "full_name", nullable = false, length = 64)
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	@Column(name = "session_id", nullable = false, length = 128)
	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	@Column(name = "ip_address", nullable = false, length = 15)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "time_entry", nullable = false, length = 14)
	public String getTimeEntry() {
		return this.timeEntry;
	}

	public void setTimeEntry(String timeEntry) {
		this.timeEntry = timeEntry;
	}

	@Column(name = "time_last_click", nullable = false, length = 14)
	public String getTimeLastClick() {
		return this.timeLastClick;
	}

	public void setTimeLastClick(String timeLastClick) {
		this.timeLastClick = timeLastClick;
	}

	@Column(name = "last_page_url", nullable = false, length = 64)
	public String getLastPageUrl() {
		return this.lastPageUrl;
	}

	public void setLastPageUrl(String lastPageUrl) {
		this.lastPageUrl = lastPageUrl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WhosOnlineId))
			return false;
		WhosOnlineId castOther = (WhosOnlineId) other;

		return ((this.getCustomerId() == castOther.getCustomerId()) || (this
				.getCustomerId() != null && castOther.getCustomerId() != null && this
				.getCustomerId().equals(castOther.getCustomerId())))
				&& ((this.getFullName() == castOther.getFullName()) || (this
						.getFullName() != null
						&& castOther.getFullName() != null && this
						.getFullName().equals(castOther.getFullName())))
				&& ((this.getSessionId() == castOther.getSessionId()) || (this
						.getSessionId() != null
						&& castOther.getSessionId() != null && this
						.getSessionId().equals(castOther.getSessionId())))
				&& ((this.getIpAddress() == castOther.getIpAddress()) || (this
						.getIpAddress() != null
						&& castOther.getIpAddress() != null && this
						.getIpAddress().equals(castOther.getIpAddress())))
				&& ((this.getTimeEntry() == castOther.getTimeEntry()) || (this
						.getTimeEntry() != null
						&& castOther.getTimeEntry() != null && this
						.getTimeEntry().equals(castOther.getTimeEntry())))
				&& ((this.getTimeLastClick() == castOther.getTimeLastClick()) || (this
						.getTimeLastClick() != null
						&& castOther.getTimeLastClick() != null && this
						.getTimeLastClick()
						.equals(castOther.getTimeLastClick())))
				&& ((this.getLastPageUrl() == castOther.getLastPageUrl()) || (this
						.getLastPageUrl() != null
						&& castOther.getLastPageUrl() != null && this
						.getLastPageUrl().equals(castOther.getLastPageUrl())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getCustomerId() == null ? 0 : this.getCustomerId()
						.hashCode());
		result = 37 * result
				+ (getFullName() == null ? 0 : this.getFullName().hashCode());
		result = 37 * result
				+ (getSessionId() == null ? 0 : this.getSessionId().hashCode());
		result = 37 * result
				+ (getIpAddress() == null ? 0 : this.getIpAddress().hashCode());
		result = 37 * result
				+ (getTimeEntry() == null ? 0 : this.getTimeEntry().hashCode());
		result = 37
				* result
				+ (getTimeLastClick() == null ? 0 : this.getTimeLastClick()
						.hashCode());
		result = 37
				* result
				+ (getLastPageUrl() == null ? 0 : this.getLastPageUrl()
						.hashCode());
		return result;
	}

}
